### ISSUE TITLE
Figure out how to set glfw options in the cmakelist itself

### ISSUE THREAD

**Issue by YMba9g8j9CJp0wLoQf5y** [hdf89shfdfs/PitoEngine#16]
The GLFW_VULKAN_STATIC CMake option makes GLFW call the Vulkan loader directly instead of dynamically loading it at runtime. Not linking against the Vulkan loader will then be a compile-time error.

I always want this to be on. Since Cmake I'm loading vulkan myself.

**Comment by hdf89shfdfs** [comment]
Fixed this issue. But also not doing vulkan.
