### ISSUE TITLE
Resizing window bug

### ISSUE THREAD

**Issue by hdf89shfdfs** [hdf89shfdfs/PitoEngine#49]
![image](https://user-images.githubusercontent.com/31327577/90986364-51c17a00-e550-11ea-9bcb-37217e0f806d.png)

When you resize the window you sometimes get artifacts?

What is happening here. It's like the application isn't clearing the backbuffer fully...

**Comment by hdf89shfdfs** [comment]
Similar:
https://stackoverflow.com/questions/37339050/when-should-i-resize-a-direct3d-11-backbuffer-to-prevent-it-being-drawn-stretche

**Comment by hdf89shfdfs** [comment]
Maximizing/moving the window makes the issue go away. But resizing it causes strange issues...

**Comment by YMba9g8j9CJp0wLoQf5y** [comment]
![image](https://user-images.githubusercontent.com/52471106/91347615-a105e580-e7b0-11ea-8d5c-a7b0a8a4ef7b.png)

Not having this problem on different computer...

**Comment by hdf89shfdfs** [comment]
Figured it out

![image](https://user-images.githubusercontent.com/31327577/91607637-35538200-e942-11ea-899b-ef4d3e915fd5.png)

This loop doesn't exit till all windows events are handled.

Basically Windows forces you to program the way they want...
